@host=https://localhost
@port=7132
@Restaurants.API_HostAddress = {{host}}:{{port}}

GET {{Restaurants.API_HostAddress}}/api/Restaurants
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/6
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/4
Accept: application/json

###

DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/3
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/Restaurants
Content-Type: application/json

{
    "Name":"celo",
    "Description":"Desc",
    "Category":"Sonnati",
    "ContactEmail":"Chelo@paz.com",
    "ContactNumber":"123345456",
    "City":"asd",
    "Street":"asdasd",
    "HasDelivery":false,
    "PostalCode":"1111111111"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/Restaurants/6
Content-Type: application/json

{
    "Name":"celo3",
    "Description":"Desc3",
    "HasDelivery":true
}
###