@host=https://localhost
@port=7132
@Restaurants.API_HostAddress = {{host}}:{{port}}

GET {{Restaurants.API_HostAddress}}/api/Restaurants
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/Dishes 
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/2/dishes/9
Accept: application/json

###

DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/3
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/Restaurants
Content-Type: application/json

{
    "Name":"celo",
    "Description":"Desc",
    "Category":"Sonnati",
    "ContactEmail":"Chelo@paz.com",
    "ContactNumber":"123345456",
    "City":"asd",
    "Street":"asdasd",
    "HasDelivery":false,
    "PostalCode":"1111111111"
}
###


PATCH {{Restaurants.API_HostAddress}}/api/Restaurants/6
Content-Type: application/json

{
    "Name":"celo3",
    "Description":"Desc3",
    "HasDelivery":true
}
###


DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/9/dishes
Content-Type: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
    "Name":"dish test",
    "Description":"desc",
    "Price": 1547000,
    "RestaurantId":2,
    "KiloCalories":123
}