@host=https://localhost
@port=7132
@Restaurants.API_HostAddress = {{host}}:{{port}}
@token=CfDJ8Fj5fa2pQ0lMgGRmkMoaqDrOA49ZmrBuBJKcm8eOWiC85qApEDgrCwMIFHF5Bt_qCUl5nvmd0DDcmMqUnHIWRx8p-X1_W9GnkQP9eUj7CLXN8qlqfyBSKZ_y6Yl9kJpDYXox4fn80_LS2zKWG98to1UIWK3rDixEnkQI0IQkRrgp-szxN8X-nAkxstMtClJFcHLCwh2g6Ap0-22aLureCogesaZmGObyuA9Qm2Icd7jxzbQatkT4ASS8CFC2yJavY-gpk85xFFKUlxHdpeBoHH7l6Qwrwpi8pKkjGBHU-j6Opp5_xOepF9kGNqnTJhJ22gtIHJo33nHY6XAi7hpgi1hWN36wgqNNu8QX6NNtjWCdDFcUTAUHiH50T4gnpbTAKqC3QsmIgozY40bG-eSEjAHZRRDAb9O8pA861-bU8moH78jogDPoZ-k8_bsa1qX2W1P-hm0df4eqIX8750ThGVJL5hxJTph1D7_Mn-Z8-JHCNqir4v7r7YPwjNg44ETizspuvXayyDByCKImFf4xGm6AvbjfRCBqJMlHnwcDh4ntRzfs6fPYcBjWDWyiash-sWgxQPPPe_-ADteuOb87tZ-6arZ3F4DSA-u8efyrvAD8rF8ZUqiz-1rB25DhrBiEgjAOsT8y-05g1nOg6QejRYsqULAL0kOZJujN8ty-ZBcQXHeygk6JKYXWDeSnH1dL3MYg7SyuD8SqPYqgBMna98lJsTLGqEW7Tajpq966P6xwq879KZ8nI3Qlx05AEzLdv-W0GIFbMD-q55JbfVgFFNe797Oalp7pLT5CxIWT4tbb
GET {{Restaurants.API_HostAddress}}/api/Restaurants
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/Dishes 
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/2/dishes/9
Accept: application/json

###

DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/3
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/Restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name":"celo",
    "Description":"Desc",
    "Category":"Sonnati",
    "ContactEmail":"Chelo@paz.com",
    "ContactNumber":"123345456",
    "City":"asd",
    "Street":"asdasd",
    "HasDelivery":false,
    "PostalCode":"1111111111"
}
###


PATCH {{Restaurants.API_HostAddress}}/api/Restaurants/6
Content-Type: application/json

{
    "Name":"celo3",
    "Description":"Desc3",
    "HasDelivery":true
}
###


DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/9/dishes
Content-Type: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
    "Name":"dish test",
    "Description":"desc",
    "Price": 1547000,
    "RestaurantId":2,
    "KiloCalories":123
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email":"testuser@test.com",
    "password":"Password!1"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email":"admin@test.com",
    "password":"Password!1"
}